### ISSUE TITLE
some requirements not clear

### ISSUE THREAD

**Issue by jbrucker** [Jomsaruj/ku-polls#2]
Your requirements are mostly good, but a few things need improvement.

number 2. specify -> specified.
number 8, modify wrong tense (same as 2)
number 3. to vague to test this
Use of word "user".  In requirement 9 its different than in others.
I think "user" itself is too vague. "Visitor" (you used one place) is more redescriptive.

Some Requirements docs have a section to define terms.

**Comment by Jomsaruj** [comment]
fixed
