### ISSUE TITLE
Some issues in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [Jomsaruj/ku-polls#3]
You used a variety of nouns: "user", "everyone" and "web visiter". How are they different? If they aren't, I suggest using just one or two terms that best describe the entities. People will assume they are different because there is no reason to use different words if the intended meaning is the same.

> 2.&nbsp;A date range for survey or poll can be specified.

> 5.&nbsp;Everyone is allowed to see the results of poll or survey.

> 8.&nbsp;After closing date, poll/survey question and the result can still be viewed but not modified.
> 9.&nbsp;Visitor can customize their survey/poll format by themselves.

As Mr James has posted in the classroom this morning, use "poll" instead of "survey" for now.

**Comment by Jomsaruj** [comment]
Issue fixed
Thank! for a very interesting suggesting
